import { ADMIN_ROLE, STUDENT_ROLE, CAREER_HEAD_ROLE, TEACHER_ROLE } from "../constants/user.constants.js";

export const CAN_DO_CRUD_ON_CAREERS = [ADMIN_ROLE];
export const CAN_DO_CRUD_ON_USERS = [ADMIN_ROLE];
export const CAN_DO_CRUD_ON_SUBJECTS = [CAREER_HEAD_ROLE, TEACHER_ROLE];
export const CAN_DO_CRUD_ON_TIMETABLES = CAN_DO_CRUD_ON_SUBJECTS;
export const CAN_DO_CRUD_ON_INSCRIPTIONS = [STUDENT_ROLE, TEACHER_ROLE, ADMIN_ROLE, CAREER_HEAD_ROLE];
export const CAN_MODERATE_INSCRIPTIONS = [TEACHER_ROLE, ADMIN_ROLE, CAREER_HEAD_ROLE];

export const CAN_APPROVE_SUBJECTS = [CAREER_HEAD_ROLE];
export const CAN_SIGN_UP_TO_SUBJECTS = [STUDENT_ROLE];